[package]
name = "catbox"
version = "0.1.0"
edition = "2021"

authors = ["XLor yjl9903@vip.qq.com"]
license = "MIT"

categories = ["command-line-utilities"]
homepage = "https://github.com/yjl9903/CatBox"
repository = "https://github.com/yjl9903/CatBox"
keywords = ["sandbox"]
readme = "README.md"
description = "A light process isolation sandbox used for competitive programming contest"

[dependencies]
cgroups-rs = "0.3.0"
structopt = "0.3"
wait-timeout = "0.2.0"
